# SPDX-License-Identifier: Apache-2.0

name: VS Code Extension

on:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      version:
        description: VS Code extension version and Git tag to publish
        required: true
        type: string
    secrets:
      VSCE_PAT:
        description: Visual Studio Marketplace access token
        required: true

permissions:
  contents: read

jobs:
  build:
    name: VS Code Extension Action - Build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run VS Code Extension
        uses: sentenz/actions/vscode-extension@e4601d50d84e629bcad4401c4d6937e3178c3000 # 1.3.0
        with:
          no-dependencies: "true"
          publish: "false"

  publish:
    name: VS Code Extension Action - Publish
    if: github.event_name == 'workflow_call'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout Release
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run VS Code Extension
        id: extension
        uses: sentenz/actions/vscode-extension@e4601d50d84e629bcad4401c4d6937e3178c3000 # 1.3.0
        with:
          version: ${{ inputs.version }}
          marketplace-token: ${{ secrets.VSCE_PAT }}
          no-dependencies: "true"
